name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Environment Variables
        run: |
          echo "GITHUB_USER_NAME=mishmanners" >> $GITHUB_ENV
          echo "GIF_OUT_PATH=dist/github-contribution-grid-snake.gif" >> $GITHUB_ENV
          echo "SVG_OUT_PATH=dist/github-contribution-grid-snake.svg" >> $GITHUB_ENV

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: VijaiRamesh
          gif_out_path: ${{ env.GIF_OUT_PATH }}
          svg_out_path: ${{ env.SVG_OUT_PATH }}

      - name: Show Build Status
        run: git status

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
        env:
          GITHUB_USER_NAME: ${{ env.GITHUB_USER_NAME }}

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

