name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          output: dist/snake.svg

      - name: push snake.svg to the output branch
        uses: actions/upload-artifact@v2
        with:
          name: snake-artifact
          path: dist/snake.svg

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: snake-artifact
          path: dist/snake.svg

      - name: push snake.svg to the output branch
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifact = await github.actions.listArtifacts({owner: context.repo.owner, repo: context.repo.repo});
            if (artifact.data.artifacts.length > 0) {
              const response = await github.actions.downloadArtifact({owner: context.repo.owner, repo: context.repo.repo, artifact_id: artifact.data.artifacts[0].id, archive_format: 'zip', path: 'dist/'});
              const fs = require('fs');
              const snakeSvg = fs.readFileSync('dist/snake.svg', 'utf-8');
              fs.writeFileSync('snake.svg', snakeSvg);
            } else {
              core.setFailed('No artifacts found');
            }

